{{- range .Values.namespaces }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: {{ .name }}
  labels:
    envrouter.io/app: notifier
  annotations:
    envrouter.io/ref: main
    envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
spec:
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
        envrouter.io/app: notifier
      annotations:
        envrouter.io/ref: main
        envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
    spec:
      containers:
        - name: notifier
          image: nginx:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  namespace: {{ .name }}
  labels:
    envrouter.io/app: reflector
  annotations:
    envrouter.io/ref: main
    envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
spec:
  selector:
    matchLabels:
      app: reflector
  template:
    metadata:
      labels:
        app: reflector
        envrouter.io/app: reflector
      annotations:
        envrouter.io/ref: main
        envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
    spec:
      containers:
        - name: reflector
          image: nginx:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
  namespace: {{ .name }}
  labels:
    envrouter.io/app: syncer
  annotations:
    envrouter.io/ref: main
    envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
spec:
  selector:
    matchLabels:
      app: syncer
  template:
    metadata:
      labels:
        app: syncer
        envrouter.io/app: syncer
      annotations:
        envrouter.io/ref: main
        envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
    spec:
      containers:
        - name: syncer
          image: nginx:latest
---
{{- end }}